# Generated by Django 2.2 on 2019-04-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('sex', models.IntegerField()),
                ('user_phone', models.CharField(max_length=20)),
                ('gmt_create', models.DateField(auto_now_add=True)),
                ('gmt_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='stock_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=6)),
                ('stock_name', models.CharField(max_length=20)),
                ('theme_id', models.CharField(max_length=20)),
                ('theme_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('stock_id',),
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=6)),
                ('owner', models.CharField(max_length=20)),
                ('gmt_create', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
