# Generated by Django 2.2 on 2019-04-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock_info',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_info',
            name='stock_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stock_info',
            name='stock_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stock_info',
            name='theme_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock_info',
            name='theme_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
