# Generated by Django 2.2 on 2019-04-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190411_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='propensity_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=6)),
                ('data', models.DateField()),
                ('total_posts', models.IntegerField()),
                ('bullish_num', models.IntegerField()),
                ('bearish_num', models.IntegerField()),
                ('neutral_num', models.IntegerField()),
                ('storage_location', models.FilePathField()),
                ('description', models.TextField(null=True)),
            ],
            options={
                'unique_together': {('stock_code', 'data')},
            },
        ),
    ]
