# Generated by Django 2.2 on 2019-04-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_propensity_statistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propensity_statistics',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='propensity_statistics',
            name='storage_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='propensity_statistics',
            unique_together={('stock_code', 'date')},
        ),
    ]
