# Generated by Django 2.2 on 2019-04-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=20, unique=True)),
                ('com_en_name', models.CharField(max_length=50, null=True, unique=True)),
                ('stock_code_A', models.IntegerField(null=True)),
                ('stock_name_A', models.CharField(max_length=20, null=True, unique=True)),
                ('stock_code_B', models.IntegerField(null=True)),
                ('stock_name_B', models.CharField(max_length=20, null=True, unique=True)),
                ('stock_code_H', models.IntegerField(null=True)),
                ('stock_name_H', models.CharField(max_length=20, null=True, unique=True)),
                ('registered_capital', models.CharField(max_length=20, null=True)),
                ('business_regist', models.IntegerField(null=True, unique=True)),
                ('introduction', models.TextField(null=True)),
                ('business_scope', models.TextField(null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'industry',
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ages', models.IntegerField()),
                ('edu_background', models.CharField(max_length=20, null=True)),
                ('post', models.CharField(max_length=20, null=True)),
                ('app_time', models.DateField()),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='related_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_type', models.CharField(max_length=20, null=True)),
                ('turnover', models.FloatField()),
                ('currency', models.CharField(max_length=20, null=True)),
                ('transaction_mode', models.CharField(max_length=20, null=True)),
                ('is_control', models.IntegerField()),
                ('notic_date', models.DateField()),
                ('company_main', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='related_company', to='company.company')),
                ('transaction_com', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_com', to='company.company')),
            ],
            options={
                'db_table': 'related_transaction',
            },
        ),
        migrations.CreateModel(
            name='option_invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_stock', models.IntegerField(null=True)),
                ('initial_balance', models.FloatField(null=True)),
                ('report_loss', models.FloatField(null=True)),
                ('end_value', models.FloatField(null=True)),
                ('percentage_invest', models.FloatField(max_length=100, null=True)),
                ('percentage_com', models.FloatField(max_length=100, null=True)),
                ('invest_com_type', models.CharField(max_length=20, null=True)),
                ('notice_date', models.DateField()),
                ('company_main', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='invest_company', to='company.company')),
                ('invest_com', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='invest_com', to='company.company')),
            ],
            options={
                'db_table': 'option_invest',
            },
        ),
        migrations.CreateModel(
            name='merge_reorganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnover', models.FloatField()),
                ('currency', models.CharField(max_length=20, null=True)),
                ('target_type', models.CharField(max_length=20, null=True)),
                ('transfer_rate', models.FloatField()),
                ('notice_date', models.DateField()),
                ('buyer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='merge_buyer', to='company.company')),
                ('company_main', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='merge_company', to='company.company')),
                ('seller', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='merge_seller', to='company.company')),
                ('transaction_target', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_target', to='company.company')),
            ],
            options={
                'db_table': 'merge_reorganization',
            },
        ),
        migrations.CreateModel(
            name='major_contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('body_relation', models.IntegerField()),
                ('others_relation', models.IntegerField()),
                ('contract_type', models.CharField(max_length=20, null=True)),
                ('contract_amount', models.CharField(max_length=20, null=True)),
                ('income_rate', models.FloatField(max_length=100)),
                ('up_and_down', models.FloatField(max_length=100)),
                ('update_date', models.DateField()),
                ('company_main', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='contract_company', to='company.company')),
                ('signing_body', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='signing_body', to='company.company')),
                ('signing_others', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='signing_others', to='company.company')),
            ],
            options={
                'db_table': 'major_contract',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='company.industry'),
        ),
        migrations.CreateModel(
            name='block_trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateField()),
                ('up_and_down', models.FloatField(max_length=100)),
                ('closing_price', models.FloatField()),
                ('transaction_price', models.FloatField()),
                ('folding_rate', models.FloatField()),
                ('volume', models.FloatField()),
                ('turnover', models.FloatField()),
                ('turnover_divide_market', models.FloatField()),
                ('buyer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='trade_buyer', to='company.company')),
                ('company_main', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='trade_company', to='company.company')),
                ('seller', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='trade_seller', to='company.company')),
            ],
            options={
                'db_table': 'block_trade',
            },
        ),
    ]
