# Generated by Django 2.2 on 2019-04-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_regist',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='com_en_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
