# Generated by Django 2.2 on 2019-05-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190428_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='com_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='merge_reorganization',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='merge_reorganization',
            name='target_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='merge_reorganization',
            name='transfer_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merge_reorganization',
            name='turnover',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),

    ]
