# Generated by Django 2.2 on 2019-05-08 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190508_1142'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='com_relation',
            table='com_relation',
        ),
    ]
