# Generated by Django 2.2 on 2019-05-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190508_1144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='com_relation',
            unique_together={('company_one', 'company_two', 'relation_name')},
        ),
    ]
