# Generated by Django 2.2 on 2019-05-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190508_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major_contract',
            name='company_main',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='major_contract',
            name='contract_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='major_contract',
            name='contract_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='major_contract',
            name='income_rate',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='major_contract',
            name='signing_body',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_body', to='company.company'),
        ),
        migrations.AlterField(
            model_name='major_contract',
            name='up_and_down',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='option_invest',
            name='end_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='option_invest',
            name='hold_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option_invest',
            name='initial_balance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='option_invest',
            name='invest_com_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='option_invest',
            name='percentage_com',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='option_invest',
            name='percentage_invest',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='option_invest',
            name='report_loss',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
