# Generated by Django 2.2 on 2019-05-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20190508_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_invest',
            name='hold_stock',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='related_transaction',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='related_transaction',
            name='is_control',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='related_transaction',
            name='related_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='related_transaction',
            name='transaction_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='related_transaction',
            name='turnover',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
