# Generated by Django 2.2 on 2019-05-09 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20190508_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='app_time',
        ),
        migrations.RemoveField(
            model_name='person',
            name='post',
        ),
        migrations.CreateModel(
            name='com_per',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=20, null=True)),
                ('app_time', models.DateField(null=True)),
                ('company', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('person', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='company.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='affiliated_com',
            field=models.ManyToManyField(through='company.com_per', to='company.company'),
        ),
    ]
