# Generated by Django 2.2 on 2019-05-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20190509_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_trade',
            name='closing_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='block_trade',
            name='folding_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='block_trade',
            name='transaction_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='block_trade',
            name='turnover',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='block_trade',
            name='turnover_divide_market',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='block_trade',
            name='up_and_down',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='block_trade',
            name='volume',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='com_per',
            name='person',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='perofcom', to='company.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='edu_background',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='cir_shareholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('nature', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('sharenum', models.CharField(blank=True, max_length=20, null=True)),
                ('percentage_share', models.CharField(blank=True, max_length=20, null=True)),
                ('change', models.CharField(blank=True, max_length=20, null=True)),
                ('percentage_change', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField()),
                ('company_main', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='cir_company', to='company.company')),
                ('shareholder', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='cir_shareholder_com', to='company.company')),
            ],
            options={
                'db_table': 'cir_shareholder',
            },
        ),
    ]
