# Generated by Django 2.2 on 2019-05-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20190523_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stock_code_A',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='stock_code_B',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='stock_code_H',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
