# Generated by Django 2.2 on 2019-05-31 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20190524_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='ages',
            new_name='age',
        ),
    ]
